# Generated by Django 3.2.9 on 2021-12-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0021_auto_20211223_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='Password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='learner',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='learner',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='learner',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='learner',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
