# Generated by Django 3.2.9 on 2021-12-23 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0022_auto_20211223_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='learner',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='learner',
            name='last_name',
        ),
    ]
