# Generated by Django 3.2.9 on 2021-12-23 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0025_alter_photo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='avatar',
            field=models.ImageField(blank=True, default='no-img.jpg', upload_to='student'),
        ),
        migrations.CreateModel(
            name='TPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='no-img.jpg', upload_to='student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
