# Generated by Django 3.2.9 on 2021-12-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0026_auto_20211223_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tphoto',
            name='avatar',
            field=models.ImageField(blank=True, default='no-img.jpg', upload_to='teacher'),
        ),
    ]
